### ISSUE TITLE
mtTag = "Mi"

### ISSUE THREAD

**Issue by creggian** [qiaseq/qiaseq-smcounter-v2#14]
I would like to raise the issue concerning this hardcoded parameter.

According to the SAM specification, it should be "MI" (all capital letter). I guess in your files you have it as it has been defined. Therefore, I suggest to let the user define the `mtTag` as parameter of `run.py`

Claudio

**Comment by rpadmanabhan** [comment]
Sorry about the issue, yes it is a good idea to move that to a generic command line argument. I will do this when I get a chance , hopefully in a week or so. You could also submit a pull request if you have already changed the code to do this.
Thanks

**Comment by rpadmanabhan** [comment]
I added the option to specify your own UMI tagname , please use the option --umiTag

**Comment by creggian** [comment]
Thanks for working on that
