### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getMeanRpb'

### ISSUE THREAD

**Issue by GAgafencu** [qiaseq/qiaseq-smcounter-v2#20]
Dear Sir,

I am trying to use qiaseq-smcounter-v2 variant caller with an input .bam file that was  generated by the submitting fastq files to QIAGEN’s QIAseq Targeted Sequencing Data Analysis Portal. 

I get the following error: 
Traceback (most recent call last):
  File "run.py", line 200, in <module>
    main(args)
  File "run.py", line 113, in main
    rpu = utils.getMeanRpb(args.bamFile, args.umiTag) 
AttributeError: 'module' object has no attribute 'getMeanRpb'

after I run this command: 
python run.py --runPath=/srv/qgen/example/smCounterV2_bam_input --bedTarget=CDHS-18021Z-150.roi.bed --bamFile=RAVVA184-diag_S2.bam --outPrefix=RAVVA184-diag --nCPU=4 --minBQ=25 --minMQ=50 --hpLen=8 --mismatchThr=6.0 --primerDist=2 --consThr=0.8 --rpu=0.0 --refGenome=/srv/qgen/data/genome/hg19/ucsc.hg19.fa --repBed=/srv/qgen/data/annotation/simpleRepeat.full.bed --srBed=/srv/qgen/data/annotation/SR_LC_SL.full.bed --bamType=raw

Could you please help me solve this error?

Thank you for your help and time.

Best wishes,
GAgafencu

**Comment by rpadmanabhan** [comment]
Sorry for the trouble. Please pull the qiaseq-dna code again and try. 
I did not sync the last commit I made on qiaseq-smcounter-v2 in the qiaseq-dna repository.

**Comment by GAgafencu** [comment]
Thank you for your help and sorry for belated response. The fix worked.
