### ISSUE TITLE
list index out of range in line 891

### ISSUE THREAD

**Issue by smzt** [qiaseq/qiaseq-smcounter-v2#4]
Dear developers,
This new version of smcounter reports an error in line 891 with this command:

$ sm_counter_v2.py --runPath /fullpath/smcounter2/variant_calling --bedTarget /fullpath/capture.bed --bamFile HD827x08-1-149_forVarCall.bam --outPrefix HD827x08-1-149 --nCPU 10  --minBQ 25 --minMQ 30 --refGenome /fullpath/Homo_sapiens.GRCh38_chr.fa --repBed /fullpath/simpleRepeat_TRF_hg38.bed --srBed /fullpath/smcounter2/SR_LC_SL_RepeatMasker_hg38.bed 
started at 2018-06-18 14:52:34.953592
('hpLen', 10)
('maxAltAllele', 2)
('minAltUMI', 3)
('srBed', /fullpath/SR_LC_SL_RepeatMasker_hg38.bed')
('bedTarget', /fullpath/capture.bed')
('mismatchThr', 6.0)
('primerDist', 2)
('refGenome', /fullpath/GRCh38/Homo_sapiens.GRCh38_chr.fa')
('bamFile', 'HD827x08-1-149_forVarCall.bam')
('primerSide', 1)
('mtThreshold', 0.8)
('nCPU', 10)
('repBed', '/fullpath/simpleRepeat_TRF_hg38.bed')
('rpb', 0.0)
('isRna', False)
('runPath', '/fullpath/smcounter2/variant_calling')
('minMQ', 30)
('outPrefix', 'HD827x08-1-149')
('minBQ', 25)
Traceback (most recent call last):
  File "/usr/local/bin/sm_counter_v2.py", line 1050, in <module>
    main(args)
  File "/usr/local/bin/sm_counter_v2.py", line 891, in main
    unitLen = lineList[4]
IndexError: list index out of range

Looking in the code, I saw that the tool searches for a 5th column from an intermediate file that is called rep.roi.bed. This file is crated as a result of this bedtool commnad.

subprocess.check_call('bedtools intersect -a ' + args.repBed + ' -b ' + args.bedTarget + '  | bedtools sort -i > rep.roi.bed', shell=True)

With this command the output will contain as many columns as the BED file given with the -a flag, which is the repBed file. The repBed file I'm using looks like a typical BED file with 4 columns so it is impossible the tool looks for a 5th (line 891) or 6th column (892).

My files might be wrong. Any help would be much appreciated.

Best regards,

Sheila

**Comment by rpadmanabhan** [comment]
Hi Sheila,

We changed the simple and tandem repeat files for smCounter-v2. Could you please use these two files : 
repBed  :   https://storage.googleapis.com/qiaseq-dna/data/annotation/simpleRepeat.full.bed
srBed     :   https://storage.googleapis.com/qiaseq-dna/data/annotation/SR_LC_SL.full.bed 

I see that you are using build 38 files,  the above ones are build 37 so you might have to lift over. 

Hope this helps, do let me know if you have further questions.

Regards,
Raghavendra

**Comment by smzt** [comment]
Dear Raghavendra,
Thanks very much for your quick reply.
I already lifted over the SR_LC_SL file and around 3,000 records could not be transformed from hg19 to hg38. Would it be possible to either get these files in hg38 or know the way they were created so I can create exactly the same BED files from scratch but for the latest genome version?

Thanks very much.

Best regards,

Sheila

**Comment by rpadmanabhan** [comment]
Sorry for the late reply , 
These are hg38 port for the files
repBed : https://storage.googleapis.com/qiaseq-rna/repeat_files/human/simpleRepeat.hg38.bed

The hg19 file was downloaded from UCSC genome browser TRF track : 
https://genome.ucsc.edu/cgi-bin/hgTrackUi?hgsid=690506849_Cg7G5BAK8kowpyF7yYokLldxGGr1&c=chr21&g=simpleRepeat

srBed : https://storage.googleapis.com/qiaseq-rna/repeat_files/human/SR_LC_SL.hg38.bed

The hg19 file came from repeatmasker with repeat class = ‘Simple_repeat’, ‘Satellite’ or ‘Low_complexity’. The original repeatmasker file can be downloaded here http://genome.ucsc.edu/cgi-bin/hgTables

**Comment by Lucioric2000** [comment]
It was a Python bug, that was fixed in the latest commits.
