### ISSUE TITLE
getMeanRpb takes just one argument but two given

### ISSUE THREAD

**Issue by smzt** [qiaseq/qiaseq-smcounter-v2#5]
Hi,
The tool throws an error in line 972. 
rpb = getMeanRpb(args.bamFile, args.isRna)

This function is defined in line 63 this way.
def getMeanRpb(bamName):

The function definition does not seem to be coherent.

Best regards,

Sheila

**Comment by rpadmanabhan** [comment]
Thanks for pointing that out. The way we use the smCounter in house , we pass the mean reads per umi/barcode as input to the program, we do have the option to calculate this on the fly as in that function. We somehow seem to have the function call wrong. 

I fixed the function call in the master branch, if you pull the latest code you should not get any error.

Also, the mtTag (barcode) is hardcoded at the top of the program to "Mi". You can change this to whatever you have the UMI in your bam tagged with. 
I will add a parameter for this when i get the chance.
