### ISSUE TITLE
required flags for the input BAM file

### ISSUE THREAD

**Issue by smzt** [qiaseq/qiaseq-smcounter-v2#6]
Dear developers,
I'd like to know which are the specific format requirements (i.e. required flags and their format) to use smcounter2 as the variant caller for a BAM file that has been obtained with other tools.

Best regards,

Sheila

**Comment by rpadmanabhan** [comment]
Sorry for the late reply. 
Please take a look at the help screen , there is an option now to specify if you have a consensus bam (--bamType).
